# Generated by Django 2.2.19 on 2022-08-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
